"""autogenerated-20220228T115940

Revision ID: 20855e200c44
Revises: b467bbaeecb2
Create Date: 2022-02-28 11:59:47.718925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20855e200c44"
down_revision = "b467bbaeecb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apikeys",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("api_key", sa.Text(), nullable=False),
        sa.Column("user_id", postgresql.UUID(), nullable=True),
        sa.Column("created_by_id", postgresql.UUID(), nullable=True),
        sa.Column("updated_by_id", postgresql.UUID(), nullable=True),
        sa.Column("deleted_by_id", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.alter_column(
        "apikeys", "user_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.create_unique_constraint(None, "apikeys", ["user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "apikeys", type_="unique")
    op.drop_table("apikeys")
    # ### end Alembic commands ###
