apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: aura
  name: console
  namespace: aura
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
    - cascadingDelete: false
      databases:
      - envVarPrefix: CONSOLE_DATABASE
        name: console
      diskAutoresize: true
      diskSize: 10
      diskType: SSD
      highAvailability: false
      name: console
      tier: db-custom-2-3840
      type: POSTGRES_14
  ingresses:
  - https://console.nais.io
  - https://console.prod-gcp.nais.io
  env:
    - name: CONSOLE_BIND_ADDRESS
      value: 0.0.0.0
    - name: CONSOLE_PORT
      value: "3000"
  port: 3000
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 10m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi
